service: RestAPI-Express-LoremIpsum # NOTE: update this with your service name

provider:
  name: aws
  runtime: nodejs8.10
  region: us-east-1

functions:
  app:
    handler: index.handler
    events:
      - http:
          path: /
          method: get
